import { Category } from "../types";
import {
  Wine,
  Flame,
  CircleDot,
  Sparkles,
  ThermometerSun,
  Soup,
  UtensilsCrossed,
  Salad,
  Fish,
  CakeSlice,
  IceCream,
  ChefHat,
  Star,
  Package,
} from "lucide-react";

export const categoryIcons: Record<string, any> = {
  wine: Wine,
  flame: Flame,
  "circle-dot": CircleDot,
  sparkles: Sparkles,
  "thermometer-sun": ThermometerSun,
  soup: Soup,
  "utensils-crossed": UtensilsCrossed,
  salad: Salad,
  fish: Fish,
  "cake-slice": CakeSlice,
  "ice-cream": IceCream,
  "chef-hat": ChefHat,
  star: Star,
  package: Package,
};

export const menuData: Category[] = [
  {
    id: "bauturi",
    title: "Băuturi",
    icon: "wine",
    image: "",
    index: 0,
    items: [
      {
        name: "LONG DRINKS",
        desc: "",
        price: "0",
        weight: "",
        image: "",
        active: true,
        isHeader: true,
        isSubHeader: false,
        index: 0,
      },
      {
        name: "Aperol Spritz",
        desc: "",
        price: "30 lei",
        weight: "250ml",
        image: "",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 1,
      },
      {
        name: "Hugo",
        desc: "",
        price: "30 lei",
        weight: "250ml",
        image: "",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 2,
      },
      {
        name: "Campari Orange",
        desc: "",
        price: "32 lei",
        weight: "250ml",
        image: "",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 3,
      },
      {
        name: "Gin Tonic",
        desc: "",
        price: "32 lei",
        weight: "250ml",
        image: "",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 4,
      },
      {
        name: "Cuba Libre",
        desc: "",
        price: "32 lei",
        weight: "250ml",
        image: "",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 5,
      },
      {
        name: "Mojito Classic",
        desc: "",
        price: "33 lei",
        weight: "250ml",
        image: "",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 6,
      },
      {
        name: "Passion Fruit Mojito",
        desc: "",
        price: "38 lei",
        weight: "250ml",
        image: "",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 7,
      },
      {
        name: "Strawberry Mojito",
        desc: "",
        price: "37 lei",
        weight: "250ml",
        image: "",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 8,
      },
      {
        name: "COCKTAILS",
        desc: "",
        price: "0",
        weight: "",
        image: "",
        active: true,
        isHeader: true,
        isSubHeader: false,
        index: 9,
      },
      {
        name: "Martini Vodka",
        desc: "",
        price: "27 lei",
        weight: "150ml",
        image: "",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 10,
      },
      {
        name: "Martini Gin",
        desc: "",
        price: "28 lei",
        weight: "150ml",
        image: "",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 11,
      },
      {
        name: "Mai Tai",
        desc: "",
        price: "32 lei",
        weight: "250ml",
        image: "",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 12,
      },
      {
        name: "Pina Colada",
        desc: "",
        price: "32 lei",
        weight: "250ml",
        image: "",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 13,
      },
      {
        name: "Cyclon",
        desc: "",
        price: "31 lei",
        weight: "250ml",
        image: "",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 14,
      },
      {
        name: "Sex on the Beach",
        desc: "",
        price: "30 lei",
        weight: "250ml",
        image: "",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 15,
      },
      {
        name: "Tequila Sunrise",
        desc: "",
        price: "33 lei",
        weight: "250ml",
        image: "",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 16,
      },
      {
        name: "Long Island Ice Tea",
        desc: "",
        price: "31 lei",
        weight: "250ml",
        image: "",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 17,
      },
      {
        name: "Cosmopolitan",
        desc: "",
        price: "31 lei",
        weight: "200ml",
        image: "",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 18,
      },
      {
        name: "Margarita",
        desc: "",
        price: "32 lei",
        weight: "150ml",
        image: "",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 19,
      },
      {
        name: "Strawberry Margarita",
        desc: "",
        price: "32 lei",
        weight: "150ml",
        image: "",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 20,
      },
      {
        name: "RĂCORITOARE",
        desc: "",
        price: "0",
        weight: "",
        image: "",
        active: true,
        isHeader: true,
        isSubHeader: false,
        index: 21,
      },
      {
        name: "Apa plata Izvorul Alb",
        desc: "",
        price: "10 lei",
        weight: "330 ml",
        image: "",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 22,
      },
      {
        name: "Apa minerala Dorna",
        desc: "",
        price: "10 lei",
        weight: "330 ml",
        image: "",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 23,
      },
      {
        name: "Coca Cola",
        desc: "",
        price: "12 lei",
        weight: "250 ml",
        image: "",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 24,
      },
      {
        name: "Coca Cola Zero",
        desc: "",
        price: "12 lei",
        weight: "250 ml",
        image: "",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 25,
      },
      {
        name: "Fanta",
        desc: "",
        price: "12 lei",
        weight: "250 ml",
        image: "",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 26,
      },
      {
        name: "Sprite",
        desc: "",
        price: "12 lei",
        weight: "250 ml",
        image: "",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 27,
      },
      {
        name: "Schweppes Tonic",
        desc: "",
        price: "12 lei",
        weight: "250 ml",
        image: "",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 28,
      },
      {
        name: "Fuzetea Lămâie",
        desc: "",
        price: "12 lei",
        weight: "250 ml",
        image: "",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 29,
      },
      {
        name: "Fuzetea Piersici",
        desc: "",
        price: "12 lei",
        weight: "250 ml",
        image: "",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 30,
      },
      {
        name: "Cappy Piersici",
        desc: "",
        price: "12 lei",
        weight: "250 ml",
        image: "",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 31,
      },
      {
        name: "Cappy Portocale",
        desc: "",
        price: "12 lei",
        weight: "250 ml",
        image: "",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 32,
      },
      {
        name: "LIMONADĂ",
        desc: "",
        price: "0",
        weight: "",
        image: "",
        active: true,
        isHeader: true,
        isSubHeader: false,
        index: 33,
      },
      {
        name: "Lemonade Clasical",
        desc: "",
        price: "21 lei",
        weight: "400 ml",
        image: "",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 34,
      },
      {
        name: "Yuzu Lemonade",
        desc: "",
        price: "24 lei",
        weight: "400 ml",
        image: "",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 35,
      },
      {
        name: "Mango Lemonade",
        desc: "",
        price: "23 lei",
        weight: "400 ml",
        image: "",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 36,
      },
      {
        name: "COFFEE illy",
        desc: "",
        price: "0",
        weight: "",
        image: "",
        active: true,
        isHeader: true,
        isSubHeader: false,
        index: 37,
      },
      {
        name: "Espresso",
        desc: "cafea espresso",
        price: "12 lei",
        weight: "40 ml",
        image: "",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 38,
      },
      {
        name: "Espresso Macchiato",
        desc: "cafea espresso cu putina crema de lapte",
        price: "14 lei",
        weight: "50 ml",
        image: "",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 39,
      },
      {
        name: "Cappuccino",
        desc: "cafea espresso cu lapte si crema de lapte",
        price: "16 lei",
        weight: "160 ml",
        image: "",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 40,
      },
      {
        name: "Cappuccino Vienez",
        desc: "cafea espresso, lapte, frisca (contine grasimi vegetale)",
        price: "16 lei",
        weight: "150 ml",
        image: "",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 41,
      },
      {
        name: "Cappuccino Caramel",
        desc: "cafea espresso cu lapte, crema de lapte si topping de caramel",
        price: "17 lei",
        weight: "160 ml",
        image: "",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 42,
      },
      {
        name: "Purcari Nocturne Sauvignon",
        desc: "",
        price: "133 lei",
        weight: "750ml",
        image: "",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 42,
      },
      {
        name: "Caffe Latte",
        desc: "cafea espresso cu lapte si spuma de lapte",
        price: "17 lei",
        weight: "200 ml",
        image: "",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 43,
      },
      {
        name: "Affogato Coffee",
        desc: "cafea espresso, inghetata de vanilie",
        price: "17 lei",
        weight: "70 ml",
        image: "",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 44,
      },
      {
        name: "Irish Coffee",
        desc: "cafea espresso, wiskey irlandez, zahar brun, frisca lichida(contine grasimi vegetale)",
        price: "20 lei",
        weight: "150 ml",
        image: "",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 45,
      },
      {
        name: "Ice Coffee",
        desc: "cafea espresso, lapte, gheata, frisca lichida (contine grasimi vegetale)",
        price: "18 lei",
        weight: "330 ml",
        image: "",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 46,
      },
      {
        name: "*Alternative vegetale (macadamia, ovaz)",
        desc: "",
        price: "5 lei",
        weight: "",
        image: "",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 47,
      },
      {
        name: "HOT TEA",
        desc: "",
        price: "0",
        weight: "",
        image: "",
        active: true,
        isHeader: true,
        isSubHeader: false,
        index: 48,
      },
      {
        name: "Verde Infuzie",
        desc: "",
        price: "20 lei",
        weight: "300 ml",
        image: "",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 49,
      },
      {
        name: "Alb Infuzie",
        desc: "",
        price: "20 lei",
        weight: "300 ml",
        image: "",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 50,
      },
      {
        name: "Negru Infuzie",
        desc: "",
        price: "20 lei",
        weight: "300 ml",
        image: "",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 51,
      },
      {
        name: "Iasomie Infuzie",
        desc: "",
        price: "20 lei",
        weight: "300 ml",
        image: "",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 52,
      },
      {
        name: "Alb cu Ghimbir Infuzie",
        desc: "",
        price: "20 lei",
        weight: "300 ml",
        image: "",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 53,
      },
      {
        name: "Fructe de Padure",
        desc: "",
        price: "20 lei",
        weight: "300 ml",
        image: "",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 54,
      },
      {
        name: "Menta Infuzie",
        desc: "",
        price: "20 lei",
        weight: "300 ml",
        image: "",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 55,
      },
      {
        name: "Musetel Infuzie",
        desc: "",
        price: "20 lei",
        weight: "300 ml",
        image: "",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 56,
      },
      {
        name: "CAFFE FRAPPE",
        desc: "",
        price: "0",
        weight: "",
        image: "",
        active: true,
        isHeader: true,
        isSubHeader: false,
        index: 57,
      },
      {
        name: "Vanilla Frappe",
        desc: "cafea espresso, lapte, gheata, frisca (contine grasimi vegetale), inghetata, topping de vanilie",
        price: "23 lei",
        weight: "330 ml",
        image: "",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 58,
      },
      {
        name: "Chocolate Frappe",
        desc: "cafea espresso, lapte, gheata, frisca (contine grasimi vegetale), inghetata, topping de ciocolata",
        price: "23 lei",
        weight: "330 ml",
        image: "",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 59,
      },
      {
        name: "Pistachio Frappe",
        desc: "cafea espresso, lapte, gheata, frisca (contine grasimi vegetale), inghetata, topping de fistic",
        price: "23 lei",
        weight: "330 ml",
        image: "",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 60,
      },
      {
        name: "VINURI",
        desc: "",
        price: "0",
        weight: "",
        image: "",
        active: true,
        isHeader: true,
        isSubHeader: false,
        index: 61,
      },
      {
        name: "VINURI ALBE",
        desc: "",
        price: "0",
        weight: "",
        image: "",
        active: true,
        isHeader: false,
        isSubHeader: true,
        index: 62,
      },
      {
        name: "Sauvignon Blanc",
        desc: "alb / sec / alc 13.5% vol",
        price: "28 / 135 lei",
        weight: "150 ml / 750 ml",
        image: "",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 64,
      },
      {
        name: "Chardonnay",
        desc: "alb / sec / alc 13.5% vol",
        price: "28 / 135 lei",
        weight: "150 ml / 750 ml",
        image: "",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 65,
      },
      {
        name: "VINURI ROSE",
        desc: "",
        price: "0",
        weight: "",
        image: "",
        active: true,
        isHeader: false,
        isSubHeader: true,
        index: 66,
      },
      {
        name: "Cabernet Sauvignon & Merlot & Rara Neagra",
        desc: "rose / sec / alc 13.5% vol",
        price: "28 / 135 lei",
        weight: "150 ml / 750 ml",
        image: "",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 68,
      },
      {
        name: "VINURI ROSII",
        desc: "",
        price: "0",
        weight: "",
        image: "",
        active: true,
        isHeader: false,
        isSubHeader: true,
        index: 69,
      },
      {
        name: "PURCARI NOCTURNE / REPUBLICA MOLDOVA",
        desc: "",
        price: "glass 150ml / bottle 750ml",
        weight: "",
        image: "",
        active: true,
        isHeader: false,
        isSubHeader: true,
        index: 70,
      },
      {
        name: "Rara Neagra",
        desc: "rosu / sec / alc 13.5% vol",
        price: "28 / 135 lei",
        weight: "150 ml / 750 ml",
        image: "",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 71,
      },
      {
        name: "PROSECCO - CANTINA MONTELLIANA / TREVISO, ITALIA",
        desc: "",
        price: "bottle 750ml",
        weight: "",
        image: "",
        active: true,
        isHeader: true,
        isSubHeader: false,
        index: 73,
      },
      {
        name: "Prosecco Glera",
        desc: "alb / brut / alc 11% vol",
        price: "135 lei",
        weight: "750 ml",
        image: "",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 74,
      },
      {
        name: "Prosecco Asolo Superiore Millesimato Glera",
        desc: "alb / brut / alc 11% vol",
        price: "135 lei",
        weight: "750 ml",
        image: "",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 75,
      },
      {
        name: "Serena",
        desc: "alb / brut / alc 11% vol",
        price: "145 lei",
        weight: "750 ml",
        image: "",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 76,
      },
      {
        name: "CHAMPAGNE",
        desc: "bottle 750ml",
        price: "0",
        weight: "",
        image: "",
        active: true,
        isHeader: true,
        isSubHeader: false,
        index: 77,
      },
      {
        name: "Moët & Chandon Brut Imperial",
        desc: "France / sec / 12% alc",
        price: "485 lei",
        weight: "750 ml",
        image: "",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 78,
      },
      {
        name: "Moët & Chandon Rose Imperial",
        desc: "France / sec / 12% alc",
        price: "625 lei",
        weight: "750 ml",
        image: "",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 79,
      },
      {
        name: "PLUM WINE",
        desc: "",
        price: "0",
        weight: "",
        image: "",
        active: true,
        isHeader: true,
        isSubHeader: false,
        index: 80,
      },
      {
        name: "JAPONIA",
        desc: "",
        price: "glass 150ml / bottle 750ml",
        weight: "",
        image: "",
        active: true,
        isHeader: true,
        isSubHeader: false,
        index: 81,
      },
      {
        name: "Choya / vin de prune",
        desc: "11.5% alc",
        price: "26 / 125 lei",
        weight: "150 ml / 750 ml",
        image: "",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 82,
      },
      {
        name: "BLENDED MALT SCOTCH WHISKY",
        desc: "",
        price: "0",
        weight: "",
        image: "",
        active: true,
        isHeader: true,
        isSubHeader: false,
        index: 83,
      },
      {
        name: "Johnnie Walker Black Label",
        desc: "40% alc.",
        price: "27 lei",
        weight: "40 ml",
        image: "",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 84,
      },
      {
        name: "Chivas Regal 12 Y.O.",
        desc: "40% alc.",
        price: "27 lei",
        weight: "40 ml",
        image: "",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 85,
      },
      {
        name: "SINGLE MALT SCOTCH WHISKY",
        desc: "",
        price: "0",
        weight: "",
        image: "",
        active: true,
        isHeader: true,
        isSubHeader: false,
        index: 86,
      },
      {
        name: "Glenfiddich 12 Y.O.",
        desc: "40% alc.",
        price: "29 lei",
        weight: "40 ml",
        image: "",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 87,
      },
      {
        name: "Balvenie 14 Y.O.",
        desc: "40% alc.",
        price: "33 lei",
        weight: "40 ml",
        image: "",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 88,
      },
      {
        name: "IRISH WHISKY",
        desc: "",
        price: "0",
        weight: "",
        image: "",
        active: true,
        isHeader: true,
        isSubHeader: false,
        index: 89,
      },
      {
        name: "Jameson",
        desc: "40% alc.",
        price: "22 lei",
        weight: "40 ml",
        image: "",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 90,
      },
      {
        name: "TENNESSEE WHISKY",
        desc: "",
        price: "0",
        weight: "",
        image: "",
        active: true,
        isHeader: true,
        isSubHeader: false,
        index: 91,
      },
      {
        name: "Jack Daniel's",
        desc: "40% alc.",
        price: "22 lei",
        weight: "40 ml",
        image: "",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 92,
      },
      {
        name: "BRANDY",
        desc: "",
        price: "0",
        weight: "",
        image: "",
        active: true,
        isHeader: true,
        isSubHeader: false,
        index: 93,
      },
      {
        name: "Metaxa 5*",
        desc: "40% alc.",
        price: "18 lei",
        weight: "40 ml",
        image: "",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 94,
      },
      {
        name: "Metaxa 7*",
        desc: "40% alc.",
        price: "20 lei",
        weight: "40 ml",
        image: "",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 95,
      },
      {
        name: "COGNAC",
        desc: "",
        price: "0",
        weight: "",
        image: "",
        active: true,
        isHeader: true,
        isSubHeader: false,
        index: 96,
      },
      {
        name: "Hennessy V.S.",
        desc: "40% alc.",
        price: "21 lei",
        weight: "40 ml",
        image: "",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 97,
      },
      {
        name: "Hennessy Fine de Cognac",
        desc: "40% alc.",
        price: "29 lei",
        weight: "40 ml",
        image: "",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 98,
      },
      {
        name: "Hennessy X.O.",
        desc: "40% alc.",
        price: "83 lei",
        weight: "40 ml",
        image: "",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 99,
      },
      {
        name: "VODKA",
        desc: "",
        price: "0",
        weight: "",
        image: "",
        active: true,
        isHeader: true,
        isSubHeader: false,
        index: 100,
      },
      {
        name: "Finlandia",
        desc: "40% alc.",
        price: "16 lei",
        weight: "40 ml",
        image: "",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 101,
      },
      {
        name: "Belvedere",
        desc: "40% alc.",
        price: "24 lei",
        weight: "40 ml",
        image: "",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 102,
      },
      {
        name: "Blavod (black vodka)",
        desc: "",
        price: "18 lei",
        weight: "40 ml",
        image: "",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 103,
      },
      {
        name: "TEQUILA",
        desc: "",
        price: "0",
        weight: "",
        image: "",
        active: true,
        isHeader: true,
        isSubHeader: false,
        index: 104,
      },
      {
        name: "Sierra Silver",
        desc: "38% alc.",
        price: "18 lei",
        weight: "40 ml",
        image: "",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 105,
      },
      {
        name: "Sierra Gold",
        desc: "38% alc.",
        price: "18 lei",
        weight: "40 ml",
        image: "",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 106,
      },
      {
        name: "BEERS",
        desc: "",
        price: "0",
        weight: "",
        image: "",
        active: true,
        isHeader: true,
        isSubHeader: false,
        index: 107,
      },
      {
        name: "Peroni Nastro Azzurro",
        desc: "5% alc.",
        price: "19 lei",
        weight: "330 ml",
        image: "",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 108,
      },
      {
        name: "Peroni Capri",
        desc: "4.2% alc.",
        price: "19 lei",
        weight: "330 ml",
        image: "",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 109,
      },
      {
        name: "Asahi",
        desc: "5% alc.",
        price: "21 lei",
        weight: "330 ml",
        image: "",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 110,
      },
      {
        name: "Heineken",
        desc: "5% alc.",
        price: "19 lei",
        weight: "330 ml",
        image: "",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 111,
      },
      {
        name: "Ursus Premium",
        desc: "5% alc.",
        price: "16 lei",
        weight: "330 ml",
        image: "",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 112,
      },
      {
        name: "Ursus Premium (fara alcool)",
        desc: "n/a",
        price: "16 lei",
        weight: "330 ml",
        image: "",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 113,
      },
      {
        name: "Ursus Black",
        desc: "5% alc.",
        price: "18 lei",
        weight: "330 ml",
        image: "",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 114,
      },
      {
        name: "Ursus Cool Lemon",
        desc: "fara alcool",
        price: "14 lei",
        weight: "330 ml",
        image: "",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 115,
      },
      {
        name: "Paulaner",
        desc: "filtrata/nefiltrata 5.5% alc.",
        price: "22 lei",
        weight: "500 ml",
        image: "",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 116,
      },
      {
        name: "Kirin (bere japoneza)",
        desc: "5% alc.",
        price: "21 lei",
        weight: "300 ml",
        image: "",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 117,
      },
    ],
  },
  {
    id: "classic-spicy",
    title: "Classic & Spicy",
    icon: "flame",
    image: "",
    index: 1,
    items: [
      {
        name: "Sake Spicy Maki",
        desc: "orez fiert, somon, ghimbir marinat, salata lolo bionda",
        price: "31 lei",
        weight: "8buc/130g",
        image: "assets/products/sake_spicy_maki.png?v=2",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 0,
      },
      {
        name: "Magura Spicy Maki",
        desc: "orez fiert, ton*, ghimbir marinat, salata lolo bionda",
        price: "33 lei",
        weight: "8buc/130g",
        image: "assets/products/magura_spicy_maki.png?v=2",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 1,
      },
      {
        name: "Ebi Spicy Maki",
        desc: "orez fiert, creveți *, ghimbir marinat, salata lolo bionda",
        price: "34 lei",
        weight: "8buc",
        image: "assets/products/ebi_spicy_maki.png?v=2",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 2,
      },
      {
        name: "Kunsei Spicy Maki",
        desc: "orez fiert, somon afumat, ghimbir marinat",
        price: "33 lei",
        weight: "8buc",
        image: "assets/products/kunsei_spicy_maki.png?v=2",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 3,
      },
      {
        name: "Unaghi Spicy Maki",
        desc: "orez fiert, anghila afumata*, ghimbir marinat",
        price: "41 lei",
        weight: "8buc",
        image: "assets/products/unaghi_spicy_maki.png?v=2",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 4,
      },
      {
        name: "Kani Spicy Maki",
        desc: "orez fiert, king crab*, ghimbir marinat",
        price: "60 lei",
        weight: "8buc",
        image: "assets/products/kani_spicy_maki.png?v=2",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 5,
      },
      {
        name: "Somon Tataki",
        desc: "somon, lamaie, salata mix, sos teriyaki",
        price: "49 lei",
        weight: "1/150g",
        image: "assets/products/somon_tataki.png?v=2",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 6,
      },
      {
        name: "Ton Tataki",
        desc: "ton*, salata mix, lamaie, sos teriyaki",
        price: "52 lei",
        weight: "1/150g",
        image: "assets/products/ton_tataki.png?v=2",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 7,
      },
      {
        name: "Piept de rață în sos Teriyaki",
        desc: "piept de rata*, sos teriyaki, ulei floarea soarelui",
        price: "55 lei",
        weight: "1/150/70g",
        image: "assets/products/piept_de_ra____n_sos_teriyaki.png?v=2",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 8,
      },
      {
        name: "Vițel în sos 'Black Pepper'",
        desc: "muschi de vita*, salata mix, rosii cherry",
        price: "62 lei",
        weight: "1/150/70g",
        image: "assets/products/vi_el__n_sos__black_pepper.png?v=2",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 9,
      },
    ],
  },
  {
    id: "maki",
    title: "Maki Rolls",
    icon: "circle-dot",
    image: "",
    index: 2,
    items: [
      {
        name: "Somon Maki",
        desc: "orez fiert, somon, ghimbir murat",
        price: "30 lei",
        weight: "8buc/130g",
        image: "assets/products/somon_maki.png?v=2",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 0,
      },
      {
        name: "Ton Maki",
        desc: "orez fiert, ton*, ghimbir murat, wasabi",
        price: "32 lei",
        weight: "8buc/130g",
        image: "assets/products/ton_maki.png?v=2",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 1,
      },
      {
        name: "Avocado Maki",
        desc: "orez fiert, avocado, ghimbir murat",
        price: "25",
        weight: "8buc/130g",
        image: "assets/products/avocado_maki.png?v=2",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 2,
      },
      {
        name: "Vegetarian Maki",
        desc: "orez fiert, avocado, castraveti, rosii, ardei gras rosu",
        price: "30 lei",
        weight: "8buc/210g",
        image: "assets/products/vegetarian_maki.png?v=2",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 3,
      },
      {
        name: "Fudziyama Maki",
        desc: "orez fiert, anghila afumata*, somon, avocado",
        price: "57 lei",
        weight: "8buc/230g",
        image: "assets/products/fudziyama_maki.png?v=2",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 4,
      },
      {
        name: "Somon Teriyaki Maki",
        desc: "orez fiert, somon prajit in sos teriyaki, crema de branza",
        price: "44 lei",
        weight: "8buc/230g",
        image: "assets/products/somon_teriyaki_maki.png?v=2",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 5,
      },
    ],
  },
  {
    id: "role",
    title: "Role Speciale",
    icon: "sparkles",
    image: "",
    index: 3,
    items: [
      {
        name: "Philadelphia Classic",
        desc: "orez fiert, somon, crema de branza, avocado",
        price: "48 lei",
        weight: "8buc/260g",
        image: "assets/products/philadelphia_classic.png?v=2",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 0,
      },
      {
        name: "Vulcan Somon",
        desc: "orez fiert, somon, avocado, castraveti, sos spicy",
        price: "51 lei",
        weight: "8buc/245g",
        image: "assets/products/vulcan_somon.png?v=2",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 1,
      },
      {
        name: "Vulcan Tuna",
        desc: "orez fiert, ton*, avocado, castraveti, sos spicy",
        price: "52 lei",
        weight: "8buc/245g",
        image: "assets/products/vulcan_tuna.png?v=2",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 2,
      },
      {
        name: "California",
        desc: "orez fiert, creveti*, ghimbir murat, avocado",
        price: "43 lei",
        weight: "8buc/230g",
        image: "assets/products/california.png?v=2",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 3,
      },
      {
        name: "California Tobico",
        desc: "orez fiert, creveti*, icre tobiko rosii*, ghimbir murat",
        price: "55 lei",
        weight: "8buc/245g",
        image: "assets/products/california_tobico.png?v=2",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 4,
      },
      {
        name: "Kunsei",
        desc: "orez fiert, somon afumat, crema de branza, ghimbir murat",
        price: "48 lei",
        weight: "8buc/245g",
        image: "assets/products/kunsei.png?v=2",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 5,
      },
      {
        name: "Kunsei de Luxe",
        desc: "orez fiert, somon afumat, crema de branza, Icre de somon*",
        price: "58 lei",
        weight: "8buc/250g",
        image: "assets/products/kunsei_de_luxe.png?v=2",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 6,
      },
      {
        name: "Philadelphia de Lux",
        desc: "orez fiert, somon, anghila afumata*, crema de branza, Icre de somon*",
        price: "65 lei",
        weight: "8buc/290g",
        image: "assets/products/philadelphia_de_lux.png?v=2",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 13,
      },
      {
        name: "Coral",
        desc: "orez fiert, anghila afumata*, creveti*, crema de branza",
        price: "65 lei",
        weight: "8buc/285g",
        image: "assets/products/coral.png?v=2",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 14,
      },
      {
        name: "Canada",
        desc: "orez fiert, anghila afumata*, crema de branza, somon, avocado",
        price: "68 lei",
        weight: "8buc/285g",
        image: "assets/products/canada.png?v=2",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 15,
      },
      {
        name: "Dragon Roșu",
        desc: "O capodoperă a contrastelor: somon fraged și anghilă afumată, îmbrățișate de un orez perfect temperat și finisate cu icre tobiko crocante.",
        price: "64 lei",
        weight: "8buc/260g",
        image: "assets/products/dragon_ro_u.png?v=2",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 1772482689874,
      },
      {
        name: "Dragon Auriu",
        desc: "orez fiert, anghila afumata*, ton*, ghimbir murat",
        price: "74 lei",
        weight: "8buc/290g",
        image: "assets/products/dragon_auriu.png?v=2",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 1772482733502,
      },
      {
        name: "Dragon Verde",
        desc: "orez fiert, avocado, crema de branza, somon",
        price: "59 lei",
        weight: "8buc/255g",
        image: "assets/products/dragon_verde.png?v=2",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 1772482735722,
      },
      {
        name: "Rainbow Dragon",
        desc: "orez fiert, creveti*, ghimbir murat, salata lolo bionda",
        price: "64 lei",
        weight: "8buc/250g",
        image: "assets/products/rainbow_dragon.png?v=2",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 1772482954769,
      },
    ],
  },
  {
    id: "role-calde",
    title: "Role Calde",
    icon: "thermometer-sun",
    image: "",
    index: 4,
    items: [
      {
        name: "Baked Shrimps",
        desc: "orez fiert, creveti*, icre tobiko rosii*, branza dura",
        price: "62 lei",
        weight: "8buc/290g",
        image: "assets/products/baked_shrimps.png?v=2",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 0,
      },
      {
        name: "Baked Unaghi",
        desc: "orez fiert, anghila afumata*, icre tobiko rosii*",
        price: "68 lei",
        weight: "8buc/290g",
        image: "assets/products/baked_unaghi.png?v=2",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 1,
      },
      {
        name: "Takusen Shrimps",
        desc: "orez fiert, creveti*, avocado, ghimbir murat",
        price: "52 lei",
        weight: "8buc/240g",
        image: "assets/products/takusen_shrimps.png?v=2",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 2,
      },
      {
        name: "Takusen Salmon",
        desc: "orez fiert, somon, avocado, ghimbir murat",
        price: "52 lei",
        weight: "8buc/245g",
        image: "assets/products/takusen_salmon.png?v=2",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 3,
      },
      {
        name: "Tempura Shrimps",
        desc: "orez fiert, creveti*, avocado, faina tempura",
        price: "47 lei",
        weight: "8buc/190/50g",
        image: "assets/products/tempura_shrimps.png?v=2",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 4,
      },
      {
        name: "Tempura Salmon",
        desc: "orez fiert, somon prajit, avocado, crema de branza",
        price: "45 lei",
        weight: "8buc/190/50g",
        image: "assets/products/tempura_salmon.png?v=2",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 5,
      },
      {
        name: "Crunch Salmon",
        desc: "orez fiert, somon, icre tobiko rosii*, faina tempura",
        price: "61 lei",
        weight: "8buc/270g",
        image: "assets/products/crunch_salmon.png?v=2",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 1772482952318,
      },
    ],
  },
  {
    id: "supe",
    title: "Supe",
    icon: "soup",
    image: "",
    index: 5,
    items: [
      {
        name: "Miso Classic",
        desc: "bulion miso, ciuperci shiitake, tofu, alge de mare, seminte de susan alb si negru",
        price: "22 lei",
        weight: "250g",
        image: "assets/products/miso_classic.png?v=2",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 0,
      },
      {
        name: "Miso Ocean",
        desc: "bulion miso, ciuperci shiitake, somon, biban de mare*, tofu, alge de mare, seminte de susan",
        price: "36 lei",
        weight: "250g",
        image: "assets/products/miso_ocean.png?v=2",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 1,
      },
      {
        name: "Karami cu pui",
        desc: "apa, pulpa de pui, taitei udon fierti, condimente karami, sare de masa",
        price: "26 lei",
        weight: "250g",
        image: "assets/products/karami_cu_pui.png?v=2",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 2,
      },
      {
        name: "Karami Seafood",
        desc: "apa, creveti*, somon, biban de mare*, condimente karami, sare de masa",
        price: "38 lei",
        weight: "250g",
        image: "assets/products/karami_seafood.png?v=2",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 3,
      },
      {
        name: "Tom Yum Classic",
        desc: "tom yam broth, creveti*, ciuperci champignon, fond de peste",
        price: "36 lei",
        weight: "250g",
        image: "assets/products/tom_yum_classic.png?v=2",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 4,
      },
      {
        name: "Tom Yum Fish",
        desc: "tom yam broth, ciuperci champignon, somon, biban de mare*, fond de peste",
        price: "38 lei",
        weight: "250g",
        image: "assets/products/tom_yum_fish.png?v=2",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 5,
      },
      {
        name: "Salmon Grill",
        desc: "bulion salmon grill s/f, somon, omleta japoneza tamago, orez fiert, seminte de susan",
        price: "36 lei",
        weight: "250g",
        image: "assets/products/salmon_grill.png?v=2",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 6,
      },
      {
        name: "Ramen cu rață",
        desc: "Secretul stă în bulionul nostru ramen, infuzat timp de 12 ore, servit cu piept de rață suculent, tăiței artizanali și ou de prepeliță.",
        price: "33 lei",
        weight: "350g",
        image: "assets/products/ramen_cu_ra_a.png?v=2",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 7,
      },
    ],
  },
  {
    id: "startere",
    title: "Startere",
    icon: "utensils-crossed",
    image: "",
    index: 6,
    items: [
      {
        name: "Edamame Classic",
        desc: "edamame pastai soia*, sare de masa",
        price: "22 lei",
        weight: "150g",
        image: "assets/products/edamame_classic.png?v=2",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 0,
      },
      {
        name: "Edamame Tempura",
        desc: "edamame boabe*, faina tempura, ulei floarea soarelui",
        price: "25 lei",
        weight: "150g",
        image: "assets/products/edamame_tempura.png?v=2",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 1,
      },
      {
        name: "Gyoza Chicken",
        desc: "gyoza cu pui si legume*, sos spicy, salata mix",
        price: "32 lei",
        weight: "130g",
        image: "assets/products/gyoza_chicken.png?v=2",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 2,
      },
      {
        name: "Gyoza Shrimps",
        desc: "gyoza cu creveti*, sos spicy, salata mix",
        price: "38 lei",
        weight: "130g",
        image: "assets/products/gyoza_shrimps.png?v=2",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 1772289594231,
      },
    ],
  },
  {
    id: "salate",
    title: "Salate",
    icon: "salad",
    image: "",
    index: 7,
    items: [
      {
        name: "Chuka Wakame",
        desc: "alge chuka*, sos de nuci, seminte de susan alb si negru",
        price: "26 lei",
        weight: "140g",
        image: "assets/products/chuka_wakame.png?v=2",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 0,
      },
      {
        name: "Avocado Salad",
        desc: "salata mix, avocado, rosii cherry, sos venegar",
        price: "27 lei",
        weight: "220g",
        image: "assets/products/avocado_salad.png?v=2",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 1,
      },
      {
        name: "Mango Salad",
        desc: "salata mix, mango, rosii cherry, sos venegar, arei gras rosu",
        price: "27 lei",
        weight: "220g",
        image: "assets/products/mango_salad.png?v=2",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 2,
      },
      {
        name: "Shrimps Tempura Salad",
        desc: "salata mix, sos tempura, creveti*, ardei gras rosu, icre tobiko rosii",
        price: "49 lei",
        weight: "220g",
        image: "assets/products/shrimps_tempura_salad.png?v=2",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 3,
      },
      {
        name: "Shrimps Avocado Salad",
        desc: "avocado, creveti*, rosii cherry, lamaie, salata mix, sos venegar",
        price: "48 lei",
        weight: "230g",
        image: "assets/products/shrimps_avocado_salad.png?v=2",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 4,
      },
      {
        name: "King Crab Salad",
        desc: "king crab*, salata mix, rosii cherry, icre tobiko rosii*, sos venegar",
        price: "98 lei",
        weight: "220g",
        image: "assets/products/king_crab_salad.png?v=2",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 5,
      },
      {
        name: "Salmon Tartar",
        desc: "somon, avocado, rosii cherry, icre tobiko rosii*, sos ponzu",
        price: "59 lei",
        weight: "230g",
        image: "assets/products/salmon_tartar.png?v=2",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 6,
      },
      {
        name: "Ton Tartar",
        desc: "ton*, avocado, rosii cherry, icre tobiko rosii*, sos ponzu",
        price: "65 lei",
        weight: "220g",
        image: "assets/products/ton_tartar.png?v=2",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 7,
      },
    ],
  },
  {
    id: "nigiri-sashimi",
    title: "Nigiri & Sashimi",
    icon: "fish",
    image: "",
    index: 8,
    items: [
      {
        name: "Somon Nigiri",
        desc: "orez fiert, somon, ghimbir murat",
        price: "22 lei",
        weight: "2buc/70g",
        image: "assets/products/somon_nigiri.png?v=2",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 0,
      },
      {
        name: "Anghila Nigiri",
        desc: "orez fiert, anghila afumata*, ghimbir murat",
        price: "33 lei",
        weight: "2buc/70g",
        image: "assets/products/anghila_nigiri.png?v=2",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 1,
      },
      {
        name: "Nigiri Creveți Tigru",
        desc: "orez fiert, creveti nigiri*, ghimbir murat",
        price: "24 lei",
        weight: "2buc/70g",
        image: "assets/products/nigiri_creve_i_tigru.png?v=2",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 2,
      },
      {
        name: "Ton Nigiri",
        desc: "orez fiert, ton*, ghimbir murat",
        price: "27 lei",
        weight: "2buc/70g",
        image: "assets/products/ton_nigiri.png?v=2",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 3,
      },
      {
        name: "Sashimi Somon",
        desc: "somon, castraveti, ghimbir murat, wasabi",
        price: "29 lei",
        weight: "65g",
        image: "assets/products/sashimi_somon.png?v=2",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 4,
      },
      {
        name: "Sashimi Anghila",
        desc: "anghila afumata*, castraveti, ghimbir murat",
        price: "43 lei",
        weight: "65g",
        image: "assets/products/sashimi_anghila.png?v=2",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 5,
      },
      {
        name: "Sashimi Creveți",
        desc: "creveti nigiri*, castraveti, ghimbir murat",
        price: "33 lei",
        weight: "65g",
        image: "assets/products/sashimi_creve_i.png?v=2",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 6,
      },
      {
        name: "Sashimi Ton",
        desc: "ton*, castraveti, ghimbir murat",
        price: "33 lei",
        weight: "65g",
        image: "assets/products/sashimi_ton.png?v=2",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 7,
      },
    ],
  },
  {
    id: "gunkan",
    title: "Gunkan",
    icon: "fish",
    image: "",
    index: 9,
    items: [
      {
        name: "Somon Tobico",
        desc: "",
        price: "20",
        weight: "45 gr",
        image: "https://i.ibb.co/bRzhpxXb/gunkan-somon-tobico.png",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 1772483366397,
      },
      {
        name: "Ton",
        desc: "",
        price: "22",
        weight: "45 gr",
        image: "https://i.ibb.co/CpM5QJR0/gunkan-ton.png",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 1772483647847,
      },
      {
        name: "Creveți",
        desc: "",
        price: "20",
        weight: "45 gr",
        image: "https://i.ibb.co/hR2Fv3PK/gunkan-creveti.png",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 1772483707633,
      },
      {
        name: "King Crab",
        desc: "",
        price: "39",
        weight: "45 gr",
        image: "https://i.ibb.co/Q7rqq27P/gunkan-king-crab.png",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 1772483751158,
      },
    ],
  },
  {
    id: "deserturi",
    title: "Deserturi",
    icon: "cake-slice",
    image: "",
    index: 10,
    items: [
      {
        name: "Tropic Roll",
        desc: "clatite, portocale , banane, creme patisserie meggle",
        price: "31 lei",
        weight: "150/40g",
        image: "assets/products/tropic_roll.png?v=2",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 0,
      },
      {
        name: "Coconut Desert",
        desc: "monin piure cocos, lapte de cocos aroy",
        price: "27 lei",
        weight: "150g",
        image: "assets/products/coconut_desert.png?v=2",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 1,
      },
      {
        name: "Mousse Maracuya",
        desc: "Echilibrul sublim între aciditatea vibrantă a fructului pasiunii și finețea unei creme catifelate. Un final tropical și rafinat.",
        price: "27 lei",
        weight: "150g",
        image: "assets/products/mousse_maracuya.png?v=2",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 2,
      },
      {
        name: "Înghețată sesame",
        desc: "Inghetata susan, seminte de susan alb si negru",
        price: "21 lei",
        weight: "150g",
        image: "assets/products/nghe_at_sesame.png?v=2",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 3,
      },
      {
        name: "Lava Cake",
        desc: "Baza de ciocolata lava cake, inghetata de vanilie, menta proaspata",
        price: "28 lei",
        weight: "130g",
        image: "assets/products/lava_cake.png?v=2",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 4,
      },
      {
        name: "Mochi",
        desc: "Prăjitură congelată cu gust și topping",
        price: "41 lei",
        weight: "120g",
        image: "assets/products/mochi.jpg?v=2",
        active: true,
        isHeader: false,
        isSubHeader: false,
        index: 5,
      },
    ],
  },
];

export const featuredItems = [
  "Ramen cu rață",
  "Dragon Roșu",
  "Philadelphia Classic",
  "Somon Tataki",
  "Edamame Tempura",
  "Tropic Roll",
];
